FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu

FROM arm64v8/ubuntu:18.04

LABEL org.opencontainers.image.authors="76527413@qq.com"

COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin

RUN cat /etc/apt/sources.list && \
    sed -i s/ports.ubuntu.com/mirrors.ustc.edu.cn/g /etc/apt/sources.list && \
    apt update -qqy && \
    rm -rf /var/lib/apt/lists/*

RUN dpkg --print-architecture