#!/bin/bash

VERSION=1.0
for tag in {$DOCKER_TAG-$VERSION,$DOCKER_TAG-$(git rev-parse --short HEAD),$DOCKER_TAG-$(date -u +"%Y-%m-%dT%H-%M-%SZ")}; do
    docker tag $IMAGE_NAME $DOCKER_REPO:$tag
    docker push $DOCKER_REPO:$tag
done
